version: 2.1

jobs:
  download_and_upload:
    docker:
      - image: cimg/node:18.17
    environment:
      PIXELDRAIN_API_KEY: 8ec6f000-e8d1-403d-820b-4324a6a68869
      TORRENT_MAGNET: "magnet:?xt=urn:btih:8F86D38E13D6D295477E3EBF05494A030333637A&dn=Ke+X.+Space-Time+Coding+Theory+in+Optical+Wireless+MIMO+Systems+2025%20%20%20%20%20%20%20%20&tr=udp://tracker.bittor.pw:1337/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.opentrackr.org:1337/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.dler.org:6969/announce%20%20%20%20%20%20%20%20&tr=udp://open.stealth.si:80/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.torrent.eu.org:451/announce%20%20%20%20%20%20%20%20&tr=udp://exodus.desync.com:6969/announce%20%20%20%20%20%20%20%20&tr=udp://open.demonii.com:1337/announce"
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            npm install webtorrent-cli

      - run:
          name: Download torrent
          command: |
            npx webtorrent download "$TORRENT_MAGNET" --out ./downloads --quiet

      - run:
          name: Upload files to PixelDrain
          command: |
            find ./downloads -type f | while read -r FILE; do
              echo "Uploading $FILE..."
              curl -T "$FILE" -u :$PIXELDRAIN_API_KEY https://pixeldrain.com/api/file
            done


workflows:
  version: 2
  download_and_upload_workflow:
    jobs:
      - download_and_upload
