version: 2.1

jobs:
  download_and_upload:
    docker:
      - image: cimg/node:18.17  # Use the Node.js 18 image, you can change to other versions
    environment:
      PIXELDRAIN_API_KEY: 8ec6f000-e8d1-403d-820b-4324a6a68869  # Replace with your PixelDrain API key
      TORRENT_MAGNET: "magnet:?xt=urn:btih:8F86D38E13D6D295477E3EBF05494A030333637A&dn=Ke+X.+Space-Time+Coding+Theory+in+Optical+Wireless+MIMO+Systems+2025%20%20%20%20%20%20%20%20&tr=udp://tracker.bittor.pw:1337/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.opentrackr.org:1337/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.dler.org:6969/announce%20%20%20%20%20%20%20%20&tr=udp://open.stealth.si:80/announce%20%20%20%20%20%20%20%20&tr=udp://tracker.torrent.eu.org:451/announce%20%20%20%20%20%20%20%20&tr=udp://exodus.desync.com:6969/announce%20%20%20%20%20%20%20%20&tr=udp://open.demonii.com:1337/announce"  # Replace with your magnet link or torrent URL
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            # Install webtorrent-cli globally
            npm install webtorrent-cli

      - run:
          name: Download torrent
          command: |
           npx webtorrent download "$TORRENT_MAGNET" --out ./downloads --quiet

      - run:
          name: Upload files to PixelDrain
          command: |
            find ./downloads -type f | while read -r FILE; do
              echo "Uploading $FILE..."
              curl -T "Authorization: Bearer $PIXELDRAIN_API_KEY" \
                   -F "file=@$FILE" \
                   https://api.pixeldrain.com/file
            done

workflows:
  version: 2
  download_and_upload_workflow:
    jobs:
      - download_and_upload
